service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  # hello:
  #   handler: src/handler.hello
  #   events:
  #     - http:
  #         method: get
  #         path: hello
  # user:
  #   handler: src/user.getUser
  #   events:
  #     - http:
  #         method: get
  #         path: getUser
  append_header:
    handler: src/header.append
    role: arn:aws:iam::546915087846:role/lambda_edge_bitbank030510
